#Problem 2
#
#Each new term in the Fibonacci sequence is generated by adding 
#the previous two terms. By starting with 1 and 2, the first 
#10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#Find the sum of all the even-valued terms in the sequence which 
#do not exceed four million.

fibonacci = [1, 2]
i = 2
term = 0
sum = 2
until term > 4_000_000 do
  term = fibonacci[i-2] + fibonacci[i-1]
  fibonacci.push term
  if term % 2 == 0 && term <= 4_000_000 then sum += term end
  i += 1
end 
print sum
