#Problem 45
#
#Triangle, pentagonal, and hexagonal numbers are
#generated by the following formulae:
#Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
#Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
#Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...
#
#It can be verified that T285 = P165 = H143 = 40755.
#
#Find the next triangle number that is also pentagonal and hexagonal.

require 'mathn'

class Integer
  def is_triangle?
    n = 0.0
    n = (-1/2) + 1/2 * Math::sqrt(1 + 8 * self)
    if n.integer? then true else false end
  end

  def is_pentagonal?
    n = 0.0
    n = (1/6) + 1/6 * Math::sqrt(1 + 24 * self)
    if n.integer? then true else false end
  end
end

n = 144
found = false
until found do
  hexagonal_number = n * ( 2 * n - 1 )
  if hexagonal_number.is_triangle?
    if hexagonal_number.is_pentagonal?
      found = true
      print hexagonal_number, "\n"
    end
  end
  n += 1
end
